[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"
  functions = "functions"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
from = "/quizzes/*"
to = "/quizzes/:splat"
status = 200
force = true
conditions = {Role = ["user"]}

[[redirects]]
from = "/quizzes/
to = "/gated/"
status = 404
force = true